using System;
using System.Collections.Generic;

namespace ZapretStudio
{
    // Локализация. Ключ -> строка на текущем языке. RU по умолчанию, EN опционально.
    static class Loc
    {
        public static string Lang = "ru";
        public static event Action LanguageChanged;

        static readonly Dictionary<string, string[]> M = new Dictionary<string, string[]>();

        static Loc()
        {
            A("nav.overview",   "Главное меню",          "Main menu");
            A("nav.strategies", "Стратегии",             "Strategies");
            A("nav.check",      "Проверка соединения",   "Connection check");
            A("nav.service",    "Служба",                "Service");
            A("nav.filters",    "Фильтры",               "Filters");
            A("nav.settings",   "Настройки",             "Settings");
            A("nav.log",        "Журнал",                "Log");
            A("nav.about",      "О проекте",             "About");
            A("common.running",   "Запущено",     "Running");
            A("common.stopped",   "Остановлено",  "Stopped");
            A("common.start",     "Запустить",    "Start");
            A("common.stop",      "Остановить",   "Stop");
            A("common.restart",   "Перезапустить","Restart");
            A("common.refresh",   "Обновить",     "Refresh");
            A("common.later",     "Позже",        "Later");
            A("common.close",     "Закрыть",      "Close");
            A("common.minimize",  "Свернуть",     "Minimize");
            A("common.maximize",  "Развернуть",   "Maximize");
            A("common.open",      "Открыть",      "Open");
            A("common.copy",      "Копировать",   "Copy");
            A("common.cancel",    "Отмена",       "Cancel");
            A("common.waiting",   "Ожидает",      "Waiting");
            A("common.checking",  "Проверяется",  "Checking");
            A("common.settings",  "Настройки",    "Settings");
            A("common.checkUpdates","Проверить обновления","Check for updates");
            A("common.button",    "кнопка",       "button");
            A("mw.verLine",     "Версия zapret {0}",  "zapret version {0}");
            A("mw.verCurrent",  "Версия zapret {0} · актуально", "zapret version {0} · up to date");
            A("mw.verUpdate",   "Доступно обновление: {0}", "Update available: {0}");
            A("mw.openGithub",  "Открыть GitHub",     "Open GitHub");
            A("mw.collapse",    "Свернуть меню",      "Collapse menu");
            A("mw.appShell",    "Оболочка v{0}",      "Shell v{0}");
            A("mw.tgVer",       "Версия TG-Proxy {0} · актуально", "TG-Proxy version {0} · up to date");
            A("mw.tgVer.none",  "TG-Proxy: не установлен", "TG-Proxy: not installed");
            A("mw.noStrats",    "Стратегии не найдены", "No strategies found");
            A("mw.startTask",   "Запуск обхода",      "Starting bypass");
            A("mw.startedToast","Обход запущен: {0}", "Bypass started: {0}");
            A("mw.stratSelected","Стратегия выбрана: {0}. Запустите обход в главном меню.", "Strategy selected: {0}. Start the bypass from the main menu.");
            A("mw.startedTitle","zapret запущен",     "zapret started");
            A("mw.startErr",    "Запуск: {0}",        "Start: {0}");
            A("mw.stopped",     "Обход остановлен",   "Bypass stopped");
            A("mw.stoppedTitle","zapret остановлен",  "zapret stopped");
            A("mw.stoppedBody", "Обход не активен",   "Bypass is not active");
            A("mw.stopErr",     "Остановка: {0}",     "Stop: {0}");
            A("mw.noStratSel",  "Стратегия не выбрана", "No strategy selected");
            A("mw.restarting",  "Перезапуск обхода…", "Restarting bypass…");
            A("mw.needAdminMsg","Для действия «{0}» нужны права администратора.\nЗапустите приложение от имени администратора.", "The \"{0}\" action requires administrator rights.\nRestart the app as administrator.");
            A("mw.needAdminLog","{0}: нет прав администратора", "{0}: no administrator rights");
            A("mw.startBypassAct","Запуск обхода",    "Starting bypass");
            A("mw.checkVer",    "Проверка версии…",   "Checking version…");
            A("mw.verFail",     "Не удалось получить версию из репозитория", "Could not fetch the version from the repository");
            A("mw.verOk",       "Актуальная версия (GitHub): {0}", "Latest version (GitHub): {0}");
            A("mw.verNew",      "Доступна версия {0} (у вас {1})", "Version {0} available (you have {1})");
            A("mw.verDlg",      "Доступна версия zapret {0} (у вас {1}).\n\nСкачать и установить обновление автоматически?", "zapret {0} is available (you have {1}).\n\nDownload and install the update automatically?");
            A("mw.verDlgTitle", "Обновление",         "Update");
            A("mw.updStart",    "Загрузка обновления {0}…", "Downloading update {0}…");
            A("mw.updProgress", "Загрузка…",          "Downloading…");
            A("mw.updFail",     "Не удалось загрузить обновление", "Failed to download the update");
            A("mw.updDone",     "Обновление установлено: версия {0}", "Update installed: version {0}");
            A("mw.noAdminWarn", "Приложение запущено без прав администратора — управление обходом и службой недоступно", "The app is running without administrator rights — bypass and service control is unavailable");
            A("mw.tray.toggle", "Запустить / остановить", "Start / stop");
            A("mw.tray.restart","Перезапустить",      "Restart");
            A("mw.tray.check",  "Проверить соединение", "Check connection");
            A("mw.tray.open",   "Открыть окно",       "Open window");
            A("mw.tray.exit",   "Выход",              "Exit");
            A("mw.tray.minTitle","{0} свёрнут",    "{0} minimized");
            A("mw.tray.minBody","Приложение работает в области уведомлений", "The app is running in the notification area");
            A("overview.title",    "Главное меню",               "Main menu");
            A("overview.sub",      "Состояние обхода и быстрые действия.", "Bypass status and quick actions.");
            A("strategies.title",  "Стратегии",           "Strategies");
            A("strategies.sub",    "Наборы параметров обхода из BAT-файлов. Логика zapret не изменяется.", "Bypass parameter sets from BAT files. Zapret logic is unchanged.");
            A("check.title",       "Проверка соединения", "Connection check");
            A("check.sub",         "Реальные проверки доступности. Результаты не подменяются.", "Real reachability checks. Results are never faked.");
            A("service.title",     "Служба Windows",      "Windows service");
            A("service.sub",       "Автозапуск обхода при старте системы. Требуются права администратора.", "Auto-start bypass at system boot. Administrator rights required.");
            A("filters.title",     "Фильтры",             "Filters");
            A("filters.sub",       "Дополнительные фильтры трафика. Изменения применяются после перезапуска обхода.", "Extra traffic filters. Changes apply after restarting the bypass.");
            A("settings.title",    "Настройки",           "Settings");
            A("settings.sub",      "Поведение приложения. Системные настройки не меняются без вашего подтверждения.", "Application behavior. System settings are not changed without your confirmation.");
            A("log.title",         "Журнал",              "Log");
            A("log.sub",           "События приложения. Хранятся только в памяти сессии.", "Application events. Kept only in session memory.");
            A("about.title",       "О проекте",           "About");
            A("about.sub",         "Информация о приложении и предупреждения о безопасности.", "Application info and safety notices.");
            A("check.tab.targets", "Адреса из targets.txt", "targets.txt hosts");
            A("check.tab.popular", "Популярные сервисы",     "Popular services");
            A("check.tab.games",   "Игровые сервисы",        "Game services");
            A("check.tab.strats",  "Проверка стратегий",     "Strategy test");
            A("check.checkAll",    "Проверить все",          "Check all");
            A("check.checkSel",    "Проверить выбранные",    "Check selected");
            A("check.export",      "Экспорт результатов",    "Export results");
            A("check.strat.run",   "Проверить эту стратегию","Test this strategy");
            A("check.strat.hint",  "Каждая стратегия запускается на короткое время, затем проверяется доступность выбранных адресов. Требуются права администратора.", "Each strategy is started briefly, then the chosen hosts are re-checked. Administrator rights required.");
            A("settings.theme",       "Тема оформления", "Theme");
            A("settings.theme.desc",  "Тёмная, AMOLED или светлая тема интерфейса.", "Dark, AMOLED or light interface theme.");
            A("settings.theme.dark",  "Тёмная",  "Dark");
            A("settings.theme.amoled","AMOLED",  "AMOLED");
            A("settings.theme.light", "Светлая", "Light");
            A("settings.lang",        "Язык интерфейса", "Interface language");
            A("settings.lang.desc",   "Russian или English. Применяется сразу.", "Russian or English. Applies immediately.");
            A("settings.sec.general",  "Основные",           "General");
            A("settings.sec.launch",   "Запуск",             "Startup");
            A("settings.sec.check",    "Проверка",           "Checking");
            A("settings.sec.dns",      "Безопасный DNS",     "Secure DNS");
            A("settings.sec.interface","Интерфейс",          "Interface");
            A("settings.sec.updates",  "Обновления",         "Updates");
            A("settings.sec.privacy",  "Конфиденциальность", "Privacy");
            A("settings.reduceMotion",     "Уменьшить анимацию", "Reduce motion");
            A("settings.reduceMotion.desc","Отключает плавные переходы интерфейса.", "Disables smooth interface transitions.");
            A("settings.tray",       "Сворачивать в трей при закрытии", "Minimize to tray on close");
            A("settings.tray.desc",  "Кнопка закрытия прячет окно в область уведомлений, приложение продолжает работать.", "The close button hides the window to the notification area; the app keeps running.");
            A("settings.notify",     "Показывать уведомления", "Show notifications");
            A("settings.notify.desc","Всплывающие уведомления Windows при запуске и остановке обхода.", "Windows toast notifications when the bypass starts or stops.");
            A("settings.autorun",     "Запускать обход при старте приложения", "Start bypass when app opens");
            A("settings.autorun.desc","Автоматически применять последнюю стратегию при открытии приложения.", "Automatically apply the last strategy when the app opens.");
            A("settings.autostart",     "Автозапуск приложения с Windows", "Launch app with Windows");
            A("settings.autostart.desc","Ярлык в автозагрузке. Настраивается вручную в системе — здесь только флаг предпочтения.", "Startup shortcut. Configured manually in the system; this is only a preference flag.");
            A("settings.tgAutostart",   "Автозапуск TG-Proxy", "Auto-start TG Proxy");
            A("settings.tgAutostart.desc","Запускать Telegram-прокси автоматически при входе в Windows.", "Start Telegram proxy automatically when Windows starts.");
            A("settings.appVer",        "Версия Lantern", "Lantern version");
            A("settings.app.downloading","Скачивание установщика...", "Downloading installer...");
            A("settings.app.installerStarted","Установщик запущен. Следуйте инструкциям.", "Installer started. Follow the instructions.");
            A("settings.timeout",     "Тайм-аут проверки соединения", "Connection check timeout");
            A("settings.timeout.desc","Максимальное ожидание ответа при проверке доступности адреса.", "Maximum wait for a response when checking a host.");
            A("settings.dns.note", "Приложение не меняет системный DNS. При проблемах с доступом рекомендуется вручную включить DNS-over-HTTPS (например, 1.1.1.1 или 8.8.8.8) в настройках сети Windows. Любое изменение DNS выполняется вами и с явным подтверждением.", "The app does not change the system DNS. If you have access issues, enable DNS-over-HTTPS manually (e.g. 1.1.1.1 or 8.8.8.8) in Windows network settings. Any DNS change is made by you, with explicit confirmation.");
            A("settings.hosts",       "Файл hosts", "hosts file");
            A("settings.hosts.warn",  "Найдены записи youtube — они могут мешать доступу. Проверьте файл hosts вручную.", "youtube entries found - they may block access. Check the hosts file manually.");
            A("settings.hosts.ok",    "Записей, мешающих YouTube, не обнаружено.", "No entries interfering with YouTube were found.");
            A("settings.hosts.needAttention", "Требует внимания", "Needs attention");
            A("settings.hosts.clean",         "Чисто", "Clean");
            A("settings.checkUpdates",     "Проверять обновления при запуске", "Check for updates on startup");
            A("settings.checkUpdates.desc","Сверять локальную версию zapret с версией в репозитории. Ничего не скачивается автоматически.", "Compare the local zapret version with the repository. Nothing is downloaded automatically.");
            A("settings.checkNow",      "Проверить сейчас", "Check now");
            A("settings.versionCheck",  "Проверка версии", "Version check");
            A("settings.localVersion",  "Локальная версия: ", "Local version: ");
            A("settings.tgVer",         "Версия Telegram-прокси", "Telegram proxy version");
            A("settings.tgVer.desc",    "Проверить установленную версию tg-ws-proxy и последнюю на GitHub.", "Check the installed tg-ws-proxy version and the latest one on GitHub.");
            A("settings.zapretVer",     "Версия zapret",      "zapret version");
            A("settings.zapretVer.desc","Проверить локальную версию zapret и последнюю в репозитории.", "Check the local zapret version and the latest one in the repository.");
            A("settings.tg.notInstalled","Не установлен",     "Not installed");
            A("settings.tg.checking",   "Проверка…",          "Checking…");
            A("settings.tg.local",      "Установлено: {0}",   "Installed: {0}");
            A("settings.tg.localUnknown","Установлен (версия неизвестна)", "Installed (version unknown)");
            A("settings.tg.latest",     "Последняя: {0}",     "Latest: {0}");
            A("settings.tg.upToDate",   "Установлена: {0} · последняя: {1}", "Installed: {0} · latest: {1}");
            A("settings.tg.update",     "Доступно обновление: {0} (у вас {1})", "Update available: {0} (you have {1})");
            A("settings.tg.fetchFail",  "Не удалось получить последнюю версию", "Could not fetch the latest version");
            A("settings.tg.latestOnly", "Последняя на GitHub: {0}", "Latest on GitHub: {0}");
            A("settings.privacy.note", "Приложение не собирает телеметрию и не отправляет данные. Проверка версии и проверка соединения обращаются только к указанным адресам и только по вашему действию.", "The app collects no telemetry and sends no data. Version and connection checks contact only the listed hosts, and only when you act.");
            A("service.sec.status",    "Состояние",             "Status");
            A("service.sec.autostart", "Стратегия автозапуска", "Auto-start strategy");
            A("service.sec.actions",   "Действия",              "Actions");
            A("service.svc",           "Служба zapret",   "zapret service");
            A("service.driver",        "Драйвер WinDivert","WinDivert driver");
            A("service.driver.desc",   "Сетевой драйвер, через который работает обход.", "The network driver the bypass runs through.");
            A("service.install",   "Установить службу", "Install service");
            A("service.remove",    "Удалить службу",    "Remove service");
            A("service.which",     "Какую стратегию ставить в службу", "Which strategy the service runs");
            A("service.which.desc","Служба будет запускать выбранную стратегию при старте Windows.", "The service will run the selected strategy at Windows startup.");
            A("service.state.running",   "Запущена",                 "Running");
            A("service.state.stopped",   "Установлена, остановлена", "Installed, stopped");
            A("service.state.absent",    "Не установлена",           "Not installed");
            A("service.strat.none",      "Стратегия не задана",      "No strategy set");
            A("service.strat.prefix",    "Стратегия: ",              "Strategy: ");
            A("service.driver.absent",   "Файл отсутствует",         "File missing");
            A("service.driver.loaded",   "Загружен",                 "Loaded");
            A("service.driver.ready",    "Готов к запуску",          "Ready to start");
            A("service.note", "Операции со службой и драйвером выполняются от имени администратора. Все команды выполняются явно, ничего не выполняется в фоне без вашего действия.", "Service and driver operations run as administrator. All commands run explicitly; nothing runs in the background without your action.");
            A("service.start",   "Запустить",  "Start");
            A("service.stop",    "Остановить", "Stop");
            A("service.pick.name","Стратегия для установки в службу", "Strategy to install into the service");
            A("service.noStrat", "Стратегия не выбрана", "No strategy selected");
            A("service.installDlg", "Установить службу zapret со стратегией:\n\n{0}\n\nСлужба будет запускаться автоматически при старте Windows. Действие выполняется с правами администратора.", "Install the zapret service with strategy:\n\n{0}\n\nThe service will start automatically at Windows boot. This action runs with administrator rights.");
            A("service.installTitle", "Установка службы", "Install service");
            A("service.installed", "Служба установлена и запущена: {0}", "Service installed and started: {0}");
            A("service.removeDlg", "Удалить службу zapret?\n\nАвтозапуск обхода при старте Windows будет отключён. Драйвер WinDivert также будет выгружен. Действие выполняется с правами администратора.", "Remove the zapret service?\n\nAuto-start of the bypass at Windows boot will be disabled. The WinDivert driver will also be unloaded. This action runs with administrator rights.");
            A("service.removeTitle", "Удаление службы", "Remove service");
            A("service.removed", "Служба удалена", "Service removed");
            A("service.started", "Служба запущена", "Service started");
            A("service.svcStopped", "Служба остановлена", "Service stopped");
            A("service.task.start",   "Запуск службы",     "Starting service");
            A("service.task.stop",    "Остановка службы",  "Stopping service");
            A("service.task.install", "Установка службы",  "Installing service");
            A("service.task.remove",  "Удаление службы",   "Removing service");
            A("service.noAdmin.msg", "Для этого действия нужны права администратора.\n\n{0} недоступно.", "This action requires administrator rights.\n\n{0} is unavailable.");
            A("service.noAdmin.title", "Нужны права администратора", "Administrator rights required");
            A("service.noAdmin.log", "{0}: нет прав администратора", "{0}: no administrator rights");
            A("state.running",  "Запущено",    "Running");
            A("state.stopped",  "Остановлено", "Stopped");
            A("mode.service",   "Служба",  "Service");
            A("mode.manual",    "Ручной",  "Manual");
            A("time.h",   " ч ",  "h ");
            A("time.m",   " мин ", "m ");
            A("time.s",   " с",   "s");
            A("ov.running",       "Запущено",   "Running");
            A("ov.stopped",       "Остановлено","Stopped");
            A("ov.sub.service",   "Служба запущена. Стратегия активна.", "Service running. Strategy active.");
            A("ov.sub.manual",    "Стратегия активна.", "Strategy active.");
            A("ov.sub.off",       "Обход не активен. Нажмите «Запустить», чтобы применить стратегию.", "Bypass is off. Press Start to apply a strategy.");
            A("ov.restart",       "Перезапустить", "Restart");
            A("ov.meta.strat",    "Активная стратегия", "Active strategy");
            A("ov.meta.mode",     "Режим запуска",      "Run mode");
            A("ov.meta.uptime",   "Время работы",       "Uptime");
            A("ov.stratNone",     "Не выбрана", "Not selected");
            A("ov.sec.components","Компоненты", "Components");
            A("ov.card.service",  "Служба",    "Service");
            A("ov.comp.active",   "Стратегия активна", "Strategy active");
            A("ov.comp.off",      "Не активно",        "Inactive");
            A("ov.wd.absent",     "Файл отсутствует",  "File missing");
            A("ov.wd.loaded",     "Драйвер загружен",  "Driver loaded");
            A("ov.wd.ready",      "Готов к запуску",   "Ready to start");
            A("ov.svc.running",   "Служба запущена",   "Service running");
            A("ov.svc.stopped",   "Остановлена",       "Stopped");
            A("ov.svc.absent",    "Не установлена",    "Not installed");
            A("ov.sec.quick",     "Быстрые действия",  "Quick actions");
            A("ov.sec.tg",        "Telegram-прокси",   "Telegram proxy");
            A("ov.zap.title",     "Обход блокировок",  "Bypass");
            A("ov.tg.install",    "Установить",        "Install");
            A("ov.tg.title",      "Telegram-прокси (tg-ws-proxy)", "Telegram proxy (tg-ws-proxy)");
            A("ov.tg.desc",       "Локальный прокси для Telegram. Включается так же, как обход.", "Local proxy for Telegram. Toggles like the bypass.");
            A("ov.tg.notInstalled","Прокси не установлен — нажмите «Скачать прокси»", "Proxy not installed — click Download proxy");
            A("ov.zap.notInstalled","Компоненты zapret не найдены — нажмите «Скачать zapret»", "Zapret components not found — click Download zapret");
            A("ov.zap.download",  "Скачать zapret", "Download zapret");
            A("ov.zap.notInstalledTitle","Не установлен", "Not installed");
            A("ov.tg.openTools",  "Инструменты",       "Tools");
            A("ov.qa.check",      "Проверить соединение", "Check connection");
            A("ov.qa.strat",      "Выбрать стратегию",    "Choose strategy");
            A("ov.qa.folder",     "Открыть папку zapret", "Open zapret folder");
            A("ov.qa.log",        "Журнал",               "Log");
            A("ov.risk", "zapret — не VPN и не шифрование трафика. Это обход DPI-блокировок. Драйвер WinDivert некоторые антивирусы помечают как RiskTool — это ожидаемо для сетевых утилит.", "zapret is not a VPN and does not encrypt traffic. It bypasses DPI blocking. Some antiviruses flag the WinDivert driver as RiskTool - this is expected for network utilities.");
            A("tg.title",     "Telegram-прокси (tg-ws-proxy)", "Telegram proxy (tg-ws-proxy)");
            A("tg.desc",      "Локальный MTProto-прокси для Telegram Desktop. Отдельная утилита Flowseal/tg-ws-proxy, скачивается по вашему подтверждению.", "Local MTProto proxy for Telegram Desktop. Separate Flowseal/tg-ws-proxy utility, downloaded on your confirmation.");
            A("tg.download",  "Скачать прокси", "Download proxy");
            A("tg.start",     "Запустить прокси", "Start proxy");
            A("tg.stop",      "Остановить прокси", "Stop proxy");
            A("tg.open",      "Открыть в Telegram", "Open in Telegram");
            A("tg.copy",      "Скопировать ссылку", "Copy link");
            A("tg.notInstalled","Прокси не установлен", "Proxy not installed");
            A("tg.installed", "Прокси установлен", "Proxy installed");
            A("tg.enable",    "Включить прокси",  "Enable proxy");
            A("tg.enabledDesc","Запускает локальный tg-ws-proxy. Работает, пока переключатель включён.", "Runs the local tg-ws-proxy. Active while the switch is on.");
            A("tg.needDownload","Сначала скачайте утилиту прокси.", "Download the proxy utility first.");
            A("tg.note", "После запуска утилита показывает ссылку для подключения (tg://proxy) в своём окне. Скопируйте её оттуда и откройте в Telegram. Приложение не подменяет и не генерирует эту ссылку.", "After launch the utility shows a connection link (tg://proxy) in its own window. Copy it from there and open it in Telegram. The app does not substitute or generate this link.");
            A("tg.dlDlg", "Скачать TgWsProxy_windows.exe из репозитория Flowseal/tg-ws-proxy?\n\nФайл будет сохранён в:\n{0}\n\nЗагрузка выполняется по HTTPS с GitHub.", "Download TgWsProxy_windows.exe from the Flowseal/tg-ws-proxy repository?\n\nThe file will be saved to:\n{0}\n\nDownload is over HTTPS from GitHub.");
            A("tg.dlTitle", "Загрузка прокси", "Download proxy");
            A("tg.dlProgress", "Загрузка...", "Downloading...");
            A("tg.dlDone", "Готово. Сохранено: {0}  ({1})", "Done. Saved: {0}  ({1})");
            A("tg.dlOk", "Telegram-прокси загружен", "Telegram proxy downloaded");
            A("tg.dlFailMsg", "Не удалось загрузить. Попробуйте открыть страницу GitHub.", "Download failed. Try opening the GitHub page.");
            A("tg.dlFail", "Загрузка прокси не удалась", "Proxy download failed");
            A("tg.startedOk", "Telegram-прокси запущен", "Telegram proxy started");
            A("tg.startedDetail", "Прокси запущен. Ссылка подключения в окне утилиты.", "Proxy started. The connection link is in the utility window.");
            A("tg.startErr", "Запуск прокси: {0}", "Proxy start: {0}");
            A("tg.startErrDetail", "Ошибка запуска: {0}", "Start error: {0}");
            A("tg.stoppedOk", "Telegram-прокси остановлен", "Telegram proxy stopped");
            A("check.selectHint", "Отметьте стратегии галочками и запустите проверку выбранных или всех.", "Tick strategies and run the check for selected or all.");
            A("check.strat.runSel","Проверить выбранные", "Test selected");
            A("check.strat.runAll","Проверить все",       "Test all");
            A("check.strat.selectAll","Выбрать все",       "Select all");
            A("check.strat.clearSel", "Снять выбор",       "Clear");
            A("check.strat.busy",  "Идёт проверка стратегий…", "Testing strategies…");
            A("check.strat.queued","В очереди",  "Queued");
            A("net.reachable",   "Доступен",    "Reachable");
            A("net.grp.other",   "Прочее",       "Other");
            A("net.grp.dns",     "Публичные DNS","Public DNS");
            A("net.grp.networks","Сети",         "Networks");
            A("net.grp.media",   "Медиа",        "Media");
            A("net.grp.msg",     "Мессенджеры",  "Messengers");
            A("net.grp.services","Сервисы",      "Services");
            A("net.grp.publishers","Издатели",   "Publishers");
            A("net.grp.consoles","Консоли",      "Consoles");
            A("cat.other",       "Другая",       "Other");
            A("desc.general", "Базовая стратегия обхода (набор по умолчанию).", "Basic bypass strategy (default set).");
            A("desc.alt",     "Альтернативный набор параметров десинхронизации DPI.", "Alternative DPI desync parameter set.");
            A("desc.fake",    "Стратегия с использованием поддельного TLS ClientHello.", "Strategy using a fake TLS ClientHello.");
            A("desc.simple",  "Упрощённый набор параметров десинхронизации.", "Simplified desync parameter set.");
            A("desc.custom",  "Пользовательская стратегия. Описание отсутствует.", "Custom strategy. No description available.");
            A("game.on.all",  "Включён (TCP и UDP)", "On (TCP and UDP)");
            A("game.on.tcp",  "Включён (TCP)",       "On (TCP)");
            A("game.on.udp",  "Включён (UDP)",       "On (UDP)");
            A("game.off",     "Выключен",            "Off");
            A("ipset.loaded", "Загружен ({0} записей)", "Loaded ({0} entries)");
            A("ipset.none",   "Отключён (заглушка)", "Disabled (stub)");
            A("ipset.empty",  "Пустой (пропускает всё)", "Empty (lets everything through)");
            A("strat.noWinws","Не найдена команда winws.exe в {0}", "winws.exe command not found in {0}");
            A("unit.b",  "Б",  "B");
            A("unit.kb", "КБ", "KB");
            A("unit.mb", "МБ", "MB");
            A("unit.gb", "ГБ", "GB");
            A("unit.perSec", "/с", "/s");
            A("tg.notInstalledErr", "Прокси не установлен", "Proxy not installed");
            A("app.errToast", "Ошибка: {0}", "Error: {0}");
            A("app.errDlg",   "Произошла ошибка:\n\n{0}", "An error occurred:\n\n{0}");
            A("app.startedLog","Приложение запущено. Папка zapret: {0}", "Application started. zapret folder: {0}");
            A("app.adminYes", "Права администратора: есть", "Administrator rights: yes");
            A("app.adminNo",  "Права администратора: нет",  "Administrator rights: no");
            A("diag.n.admin",     "Права администратора", "Administrator rights");
            A("diag.v.adminYes",  "Есть",                 "Yes");
            A("diag.v.adminNo",   "Нет — служба и драйвер недоступны", "No — service and driver unavailable");
            A("diag.n.root",      "Папка zapret",         "zapret folder");
            A("diag.v.notFound",  "Не найдена",           "Not found");
            A("diag.v.present",   "На месте",             "Present");
            A("diag.v.absent",    "Отсутствует",          "Missing");
            A("diag.n.winws",     "winws.exe",            "winws.exe");
            A("diag.n.wdFile",    "Драйвер WinDivert (файл)", "WinDivert driver (file)");
            A("diag.v.wdQuar",    "Отсутствует (возможно, в карантине антивируса)", "Missing (possibly quarantined by antivirus)");
            A("diag.n.wdLoaded",  "Драйвер WinDivert (загружен)", "WinDivert driver (loaded)");
            A("diag.v.loaded",    "Загружен",             "Loaded");
            A("diag.v.wdNotLoaded","Не загружен — запустится вместе со стратегией", "Not loaded — will start with the strategy");
            A("diag.n.winwsProc", "Процесс winws",        "winws process");
            A("diag.v.running",   "Запущен",              "Running");
            A("diag.v.stopped",   "Остановлен",           "Stopped");
            A("diag.n.service",   "Служба zapret",        "zapret service");
            A("diag.v.svcRunning","Запущена",             "Running");
            A("diag.v.svcStopped","Установлена, остановлена", "Installed, stopped");
            A("diag.v.svcAbsent", "Не установлена",       "Not installed");
            A("diag.n.strats",    "Стратегии (.bat)",     "Strategies (.bat)");
            A("diag.v.stratCount","{0} шт.",              "{0} pcs.");
            A("diag.v.stratNone", "Не найдены",           "Not found");
            A("diag.n.gameFilter","Игровой фильтр",       "Game filter");
            A("diag.n.ipset",     "IPSet-фильтр",         "IPSet filter");
            A("diag.n.targets",   "Список целей проверки","Check target list");
            A("diag.v.targetCount","{0} адресов",         "{0} hosts");
            A("diag.v.targetsAbsent","targets.txt отсутствует", "targets.txt missing");
            A("diag.n.hosts",     "hosts: записи youtube","hosts: youtube entries");
            A("diag.v.hostsFound","Найдены — могут мешать доступу", "Found — may interfere with access");
            A("diag.v.hostsClean","Чисто",                "Clean");
            A("diag.n.localVer",  "Локальная версия zapret", "Local zapret version");
            A("diag.head",        "=== {0} · диагностика ===", "=== {0} · diagnostics ===");
            A("diag.guiVer",      "Версия GUI: {0}",      "GUI version: {0}");
            A("diag.zapret",      "zapret: {0}",          "zapret: {0}");
            A("diag.folder",      "Папка: {0}",           "Folder: {0}");
            A("diag.none",        "(нет)",                "(none)");
            A("diag.admin",       "Админ: {0}",           "Admin: {0}");
            A("diag.yes",         "да",                   "yes");
            A("diag.no",          "нет",                  "no");
            A("diag.events",      "--- последние события ---", "--- recent events ---");            A("net.partial",     "Частично",    "Partial");
            A("net.unreachable", "Недоступен",  "Unreachable");
            A("net.timeout",     "Тайм-аут",    "Timed out");
            A("net.errDns",      "Ошибка DNS",  "DNS error");
            A("net.errTls",      "Ошибка TLS",  "TLS error");
            A("net.err",         "Ошибка",      "Error");
            A("net.checking",    "Проверяется", "Checking");
            A("net.d.icmpOk",    "ICMP ответ получен", "ICMP reply received");
            A("net.d.icmpNone",  "Нет ICMP ответа",    "No ICMP reply");
            A("net.d.noReply",   "Нет ответа",         "No reply");
            A("net.d.badUrl",    "Некорректный URL",   "Invalid URL");
            A("net.d.tcpNone",   "TCP: нет соединения","TCP: no connection");
            A("net.d.noStatus",  "Ответ без статуса",  "Response without status");
            A("net.d.empty",     "Пустой ответ",       "Empty response");
            A("net.listEmpty",   "Список пуст.",       "The list is empty.");
            A("net.notFound",    "Стратегии (general*.bat) не найдены.", "Strategies (general*.bat) not found.");
            A("net.select",      "Выбрать {0}",        "Select {0}");
            A("net.ms",          " мс",   " ms");
            A("check.run.started","Проверка соединения: запущено ({0} адресов)", "Connection check: started ({0} hosts)");
            A("check.run.stopped","Проверка соединения: остановлено", "Connection check: stopped");
            A("check.run.done",  "Проверка соединения: завершено", "Connection check: finished");
            A("check.export.head","Проверка соединения - {0}", "Connection check - {0}");
            A("check.export.ok", "Результаты сохранены: {0}", "Results saved: {0}");
            A("check.export.err","Не удалось сохранить: {0}", "Failed to save: {0}");
            A("check.strat.noAdmin", "Для проверки стратегии нужны права администратора (запуск winws).", "Strategy testing requires administrator rights (to launch winws).");
            A("check.strat.confirmOne", "Проверка временно запустит winws со стратегией \"{0}\", проверит доступность нескольких адресов и остановит обход.\n\nТекущий обход будет остановлен. Продолжить?", "The check will briefly launch winws with strategy \"{0}\", test a few hosts, and then stop the bypass.\n\nThe current bypass will be stopped. Continue?");
            A("check.strat.confirmOne.title", "Проверка стратегии", "Strategy test");
            A("check.strat.confirmAll", "Проверка последовательно запустит winws для {0} стратегий, по очереди проверит доступность адресов и остановит обход после каждой.\n\nТекущий обход будет остановлен. Продолжить?", "The check will launch winws for {0} strategies one by one, test the hosts for each, and stop the bypass after each.\n\nThe current bypass will be stopped. Continue?");
            A("check.strat.confirmAll.title", "Проверка стратегий", "Strategy tests");
            A("check.strat.noneSel", "Стратегии для проверки не выбраны", "No strategies selected for testing");
            A("check.strat.stopped", "Остановлено", "Stopped");
            A("check.strat.launching", "Запуск стратегии...", "Launching strategy...");
            A("check.strat.probing", "Проверка: {0}...", "Checking: {0}...");
            A("check.strat.err", "Ошибка", "Error");
            A("check.strat.errDetail", "Ошибка проверки: {0}", "Test error: {0}");
            A("check.strat.errLog", "Проверка стратегии {0}: {1}", "Strategy test {0}: {1}");
            A("check.strat.cancelled", "Проверка остановлена. Обход выключен.", "Test stopped. Bypass is off.");
            A("check.strat.pass", "Пройдено", "Passed");
            A("check.strat.partial", "Частично", "Partial");
            A("check.strat.fail", "Не пройдено", "Failed");
            A("check.strat.resultLine", "Доступно {0} из {1} адресов. Обход остановлен после проверки.", "{0} of {1} hosts reachable. Bypass stopped after the test.");
            A("check.strat.resultLog", "Проверка стратегии {0}: {1}/{2}", "Strategy test {0}: {1}/{2}");
            A("check.strat.batchStopped", "Проверка стратегий: остановлено", "Strategy tests: stopped");
            A("check.strat.batchDone", "Проверка стратегий: завершено", "Strategy tests: finished");
            A("dl.title",     "Компоненты zapret не найдены", "Zapret components not found");
            A("dl.desc",      "Не найдены файлы bin, winws.exe. Можно скачать последний релиз с GitHub. Приложение распакует и настроит всё автоматически. Ничего не запускается без вашего подтверждения.", "bin, winws.exe was not found. You can download the latest GitHub release. The app will unpack and set everything up automatically. Nothing runs without your confirmation.");
            A("dl.download",  "Скачать с GitHub", "Download from GitHub");
            A("dl.openPage",  "Открыть страницу релизов", "Open releases page");
            A("dl.choose",    "Указать папку вручную", "Choose folder manually");
            A("dl.exit",      "Выход", "Exit");
            A("dl.downloaded","Скачано", "Downloaded");
            A("dl.speed",     "Скорость", "Speed");
            A("dl.elapsed",   "Время", "Elapsed");
            A("dl.when",      "Завершено", "Finished at");
            A("dl.extracting","Распаковка...", "Extracting...");
            A("dl.done",      "Готово. Перезапустите приложение.", "Done. Please restart the application.");
            A("dl.pickFolder","Выберите папку zapret (где есть bin\\winws.exe)", "Choose the zapret folder (containing bin\\winws.exe)");
            A("dl.noWinws",   "В выбранной папке не найден bin\\winws.exe.", "bin\\winws.exe was not found in the selected folder.");
            A("dl.confirm",   "Скачать последний релиз zapret с GitHub и настроить его?\n\nИсточник: {0}\nПапка назначения: {1}\n\nЗагрузка по HTTPS. Ничего не запускается автоматически.", "Download the latest zapret release from GitHub and set it up?\n\nSource: {0}\nDestination: {1}\n\nDownload over HTTPS. Nothing runs automatically.");
            A("dl.confirmTitle","Загрузка zapret", "Download zapret");
            A("dl.progress",  "Загрузка...", "Downloading...");
            A("dl.failZip",   "Не удалось загрузить архив. Проверьте соединение или откройте страницу релизов.", "Failed to download the archive. Check your connection or open the releases page.");
            A("dl.installed", "zapret установлен: {0}", "zapret installed: {0}");
            A("dl.failExtract","Не удалось распаковать или файлы неполные{0}.", "Failed to extract or files are incomplete{0}.");
            A("dl.dlErr",     "Ошибка загрузки: {0}", "Download error: {0}");
            // Фильтры
            A("filters.sec.game",  "Игровой фильтр", "Game filter");
            A("filters.game",      "Обход для игр (порты выше 1023)", "Bypass for games (ports above 1023)");
            A("filters.game.desc", "Расширяет обход на игровой трафик по TCP и UDP. Может помочь с играми, использующими нестандартные порты.", "Extends the bypass to game traffic over TCP and UDP. May help with games using non-standard ports.");
            A("filters.sec.ipset", "IPSet-фильтр", "IPSet filter");
            A("filters.ipset",     "Использовать список IP (ipset-all.txt)", "Use IP list (ipset-all.txt)");
            A("filters.ipset.on",  "Применять обход к адресам из списка ipset-all.txt.", "Apply the bypass to addresses from ipset-all.txt.");
            A("filters.ipset.off", "Файл lists/ipset-all.txt не найден — фильтр недоступен.", "lists/ipset-all.txt not found - filter unavailable.");
            A("filters.restart.note", "Изменения фильтров вступят в силу после перезапуска обхода.", "Filter changes take effect after restarting the bypass.");
            A("filters.restartNow",   "Перезапустить сейчас", "Restart now");
            // Стратегии
            A("strat.all",        "Все",        "All");
            A("strat.favorites",  "Избранное",  "Favorites");
            A("strat.search",     "Поиск стратегии", "Search strategy");
            A("strat.filterPrefix","Фильтр: ",  "Filter: ");
            A("strat.nothing",    "Ничего не найдено.", "Nothing found.");
            A("strat.pickHint",   "Нажмите на стратегию, чтобы выбрать её. Запуск обхода — в главном меню.", "Click a strategy to select it. Start the bypass from the main menu.");
            A("strat.current",    "Текущая",    "Current");
            A("strat.favAdd",     "В избранное: ",       "Add to favorites: ");
            A("strat.favRemove",  "Убрать из избранного: ", "Remove from favorites: ");
            A("strat.favAdded",   "Добавлено в избранное: {0}", "Added to favorites: {0}");
            A("strat.favRemoved", "Убрано из избранного: {0}", "Removed from favorites: {0}");
            // Журнал
            A("log.clear",   "Очистить",       "Clear");
            A("log.copy",    "Копировать всё",  "Copy all");
            A("log.empty",   "Журнал пуст.",   "Log is empty.");
            A("log.copied",  "Журнал скопирован в буфер обмена", "Log copied to clipboard");
            A("log.copyErr", "Копирование: {0}", "Copy: {0}");
            A("log.saved",   "Журнал сохранён: {0}", "Log saved: {0}");
            A("log.saveErr", "Сохранение: {0}", "Save: {0}");
            A("log.diagCopied", "Диагностика скопирована (имя пользователя и пути замаскированы)", "Diagnostics copied (username and paths masked)");
            A("log.diagErr", "Диагностика: {0}", "Diagnostics: {0}");
            A("log.cleared", "Журнал очищен",  "Log cleared");
            A("log.search",  "Поиск по журналу", "Search log");
            A("log.pause",   "Пауза",     "Pause");
            A("log.resume",  "Возобновить","Resume");
            A("log.autoscroll","Автопрокрутка", "Auto-scroll");
            A("log.copyBtn", "Копировать", "Copy");
            A("log.save",    "Сохранить",  "Save");
            A("log.diag",    "Копировать диагностику", "Copy diagnostics");
            // О проекте
            A("about.appName",   "{0} · графическая оболочка zapret", "{0} · zapret graphical shell");
            A("about.versionLine","Версия оболочки {0} · zapret {1}", "Shell version {0} · zapret {1}");
            A("about.intro",     "Оболочка не изменяет внутреннюю логику zapret. Она использует существующие скрипты и бинарные файлы как исполнительный слой и показывает реальные результаты.", "The shell does not change zapret's internal logic. It uses the existing scripts and binaries as an execution layer and shows real results.");
            A("about.sec.versions", "Версии", "Versions");
            A("about.ver.app",    "Версия приложения", "App version");
            A("about.ver.app.desc","Графическая оболочка Lantern", "Lantern graphical shell");
            A("about.ver.zapret", "Версия zapret", "zapret version");
            A("about.ver.zapret.desc","Движок обхода DPI (bol-van / Flowseal)", "DPI bypass engine (bol-van / Flowseal)");
            A("about.ver.tg",     "Версия Telegram-прокси", "Telegram proxy version");
            A("about.ver.tg.desc","Локальный tg-ws-proxy", "Local tg-ws-proxy");
            A("about.ver.repo",   "Репозиторий приложения", "App repository");
            A("about.sec.links", "Ссылки", "Links");            A("about.link.flowseal","Сборка и стратегии обхода", "Build and bypass strategies");
            A("about.link.engine", "Оригинальный движок DPI-обхода", "Original DPI bypass engine");
            A("about.link.windivert","Сетевой драйвер перехвата пакетов", "Packet capture network driver");
            A("about.sec.licenses","Лицензии", "Licenses");
            A("about.lic.engine",  "zapret (движок)", "zapret (engine)");
            A("about.lic.flowseal","Сборка Flowseal и оболочка", "Flowseal build and shell");
            A("about.sec.integrity","Проверка целостности", "Integrity check");
            A("about.verify",     "Проверить SHA-256", "Verify SHA-256");
            A("about.checksums",  "Контрольные суммы файлов", "File checksums");
            A("about.checksums.desc","Сверяет ключевые файлы с SHA256SUMS.txt из поставки. Помогает убедиться, что файлы не подменены.", "Compares key files against the bundled SHA256SUMS.txt. Helps confirm files were not tampered with.");
            A("about.sums.absent","Файл SHA256SUMS.txt не найден в папке zapret.", "SHA256SUMS.txt not found in the zapret folder.");
            A("about.sums.missing","файл отсутствует", "file missing");
            A("about.sums.match", "совпадает", "matches");
            A("about.sums.mismatch","НЕ совпадает", "does NOT match");
            A("about.sums.summary","Проверено: OK {0}, несовпадений {1}, отсутствует {2}", "Checked: OK {0}, mismatches {1}, missing {2}");
            A("about.warn", "Скачивайте zapret только из официального репозитория Flowseal. Поддельные страницы и сборки могут содержать вредоносный код. Проверяйте контрольные суммы.", "Download zapret only from the official Flowseal repository. Fake pages and builds may contain malicious code. Verify checksums.");
            // Автоподбор стратегии
            A("check.strat.autoPick", "Автоподбор лучшей", "Auto-pick best");
            A("check.strat.autoPickConfirm", "Будут проверены все стратегии ({0} шт.) и выбрана лучшая.\n\nЭто займёт время. Продолжить?", "All strategies ({0}) will be tested and the best one selected.\n\nThis will take time. Continue?");
            A("check.strat.autoPickStart", "Автоподбор: проверка {0} стратегий…", "Auto-pick: testing {0} strategies…");
            A("check.strat.autoPickDone", "Лучшая стратегия: {0} ({1}/{2} доступно).\nСтратегия выбрана автоматически.", "Best strategy: {0} ({1}/{2} reachable).\nStrategy selected automatically.");
            A("check.strat.autoPickNone", "Ни одна стратегия не обеспечила доступ. Проверьте соединение.", "No strategy provided access. Check your connection.");
            // Автопереключение (watchdog)
            A("mw.watchdogOn", "Автопереключение включено (каждые {0} мин.)", "Auto-switch enabled (every {0} min)");
            A("mw.watchdogCheck", "Автопереключение: проверка соединения…", "Auto-switch: checking connection…");
            A("mw.watchdogFail", "Автопереключение: текущая стратегия не работает, поиск замены…", "Auto-switch: current strategy failed, searching for alternative…");
            A("mw.watchdogSwitch", "Автопереключение: переход на {0}", "Auto-switch: switching to {0}");
            A("mw.watchdogSwitchTitle", "Стратегия переключена", "Strategy switched");
            A("mw.watchdogNone", "Автопереключение: рабочая стратегия не найдена", "Auto-switch: no working strategy found");
            A("mw.watchdogNoneTitle", "Обход не работает", "Bypass not working");
            A("settings.sec.watchdog", "Автопереключение", "Auto-switch");
            A("settings.watchdog", "Автопереключение стратегии", "Auto-switch strategy");
            A("settings.watchdog.desc", "Периодически проверять соединение и автоматически переключать стратегию, если текущая не работает.", "Periodically check connection and automatically switch strategy if the current one fails.");
            A("settings.watchdog.interval", "Интервал проверки", "Check interval");
            A("settings.watchdog.interval.desc", "Как часто проверять работоспособность текущей стратегии.", "How often to check the current strategy's connectivity.");
            A("time.min", "мин", "min");
            // Статистика трафика
            A("ov.sec.traffic", "Трафик", "Traffic");
            A("ov.traffic.down", "Загрузка", "Download");
            A("ov.traffic.up", "Отдача", "Upload");
            A("ov.traffic.totalDown", "Всего загружено", "Total downloaded");
            A("ov.traffic.totalUp", "Всего отправлено", "Total uploaded");
            // DNS-over-HTTPS
            A("filters.sec.doh", "DNS-over-HTTPS", "DNS-over-HTTPS");
            A("filters.doh", "Включить DNS-over-HTTPS", "Enable DNS-over-HTTPS");
            A("filters.doh.desc", "Шифрует DNS-запросы. Требуются права администратора. Применяется через реестр Windows.", "Encrypts DNS queries. Requires administrator rights. Applied via Windows registry.");
            A("doh.enabled", "DNS-over-HTTPS включён", "DNS-over-HTTPS enabled");
            A("doh.disabled", "DNS-over-HTTPS выключен", "DNS-over-HTTPS disabled");
            A("doh.err", "DoH: {0}", "DoH: {0}");
            A("doh.auto", "Авто", "Auto");
            A("doh.require", "Обязательно", "Required");
            A("doh.off", "Выключен", "Off");
            // Визуальный редактор списков
            A("filters.sec.lists", "Списки (редактор)", "Lists (editor)");
            A("filters.list.add", "Добавить", "Add");
            A("filters.list.del", "Удалить", "Remove");
            A("filters.list.count", "Записей: {0}", "Entries: {0}");
            A("filters.list.added", "Добавлено: {0}", "Added: {0}");
            A("filters.list.removed", "Удалено: {0}", "Removed: {0}");
            // Обновление списков
            A("filters.updateLists", "Обновить списки с GitHub", "Update lists from GitHub");
            A("filters.updatingLists", "Обновление списков…", "Updating lists…");
            A("filters.listsUpdated", "Список ipset обновлён ({0} записей)", "IPSet list updated ({0} entries)");
            A("filters.listsErr", "Не удалось обновить списки: {0}", "Failed to update lists: {0}");
            // Changelog
            A("mw.changelog", "Что нового", "What's new");
            // Сравнение стратегий
            A("check.strat.comparison", "Сравнение стратегий (по эффективности):", "Strategy comparison (by effectiveness):");
            // Профили
            A("settings.sec.profiles", "Профили", "Profiles");
            A("settings.profile.save", "Сохранить текущий профиль", "Save current profile");
            A("settings.profile.load", "Загрузить", "Load");
            A("settings.profile.del", "Удалить", "Delete");
            A("settings.profile.namePrompt", "Имя профиля:", "Profile name:");
            A("settings.profile.saved", "Профиль сохранён: {0}", "Profile saved: {0}");
            A("settings.profile.loaded", "Профиль загружен: {0}", "Profile loaded: {0}");
            A("settings.profile.deleted", "Профиль удалён: {0}", "Profile deleted: {0}");
            A("settings.updateNow", "Обновить", "Update");
            A("settings.latestVer", "Последняя версия", "Latest version");
        }

        static void A(string key, string ru, string en) { M[key] = new[] { ru, en }; }

        public static string T(string key)
        {
            string[] v;
            if (!M.TryGetValue(key, out v)) return key;
            return Lang == "en" ? v[1] : v[0];
        }

        public static void Load()
        {
            string l = Core.Get("lang", "ru");
            Lang = (l == "en") ? "en" : "ru";
        }

        public static void SetLang(string lang)
        {
            lang = (lang == "en") ? "en" : "ru";
            if (lang == Lang) return;
            Lang = lang;
            Core.Set("lang", lang); Core.SaveConfig();
            if (LanguageChanged != null) LanguageChanged();
        }
    }
}
